# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [ importlib_metadata<5]
-   repo: local
    hooks:
    -   id: commitizen check
        name: "Check if the commit message follows certain rules"
        entry: cz check --commit-msg-file
        stages: [commit-msg]
        language: python
        require_serial: true
    -   id: unittests
        name: unittests
        entry: python3 -m unittest discover
        pass_filenames: false
        language: python
        additional_dependencies:
            - typing_extensions
    -   id: doctests
        name: doctests
        entry: python3 -m tests.test_fagus doctest
        pass_filenames: false
        language: python
        additional_dependencies:
            - typing_extensions
    -   id: mypy
        name: mypy
        description: ''
        entry: mypy
        language: python
        'types_or': [ python, pyi ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
        require_serial: true
        additional_dependencies: [tokenize-rt]
        minimum_pre_commit_version: '2.9.2'
    -   id: md-toc
        name: Update TOC in markdown-files
        language: python
        entry: md_toc
        args: [-p, -s1, github]
        types: [markdown]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
        -   id: check-json
        -   id: check-toml
        -   id: check-yaml
        -   id: check-xml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
