# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: commitizen check
        name: "Check if the commit message follows certain rules"
        entry: cz check --commit-msg-file
        stages: [commit-msg]
        language: python
        require_serial: true
    -   id: unittests
        name: unittests
        entry: python3 -m unittest discover
        pass_filenames: false
        language: python
    -   id: doctests
        name: doctests
        entry: python3 -m tests.test_fagus doctest
        pass_filenames: false
        language: python
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
        -   id: check-json
        -   id: check-toml
        -   id: check-yaml
        -   id: check-xml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
