[tool.poetry]
name = "treeo"
version = "0.1.0"
description = "Library to easily create, edit and traverse nested objects of dicts and lists in Python"
authors = ["Lukas Neuenschwander <fjellvannet@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "^22.3.0", python = "^3.6.2"}
flake8 = "^4.0.1"
commitizen = {version = "^2.24.0", python = "^3.6.2"}
pre-commit = [
    {version = "^2.17.0, <2.18.0", python = "^3.6.1, <3.7.0"},
    {version = "^2.18.0", python = "^3.7.0"}
]

[tool.black]
line-length=120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
